DATASET:
    NAME: "trans10k_boundary"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 16
    BATCH_SIZE: 8
    CROP_SIZE: 769
    MODEL_SAVE_DIR: 'workdirs/debug'
TEST:
    BATCH_SIZE: 1

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "TransLab"
    BACKBONE: "resnet50"

